name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -q
    - uses: taiki-e/install-action@v2
      with:
        tool: nextest
    - name: Run tests
      run: cargo nextest run --all-features --all-targets
